openapi: 3.0.1
info:
  title: Ravn challenge V2 Rony Garcia
  description: 'This is de API documentation for the Ravn challenge.'
paths:
  $include: "paths/paths.yaml"
components:
  schemas:
    $include: "schemas/schemas.yaml"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []