const products = [
    {
        id: 10002,
        name: "Brownies",
        price: 3.5,
        quantity: 20,
        category_id: 1,
    },
    {
        id: 10003,
        name: "macarons",
        price: 1.5,
        quantity: 15,
        category_id: 1,
    },
    {
        id: 10004,
        name: "Sweet bread",
        price: 3.5,
        quantity: 20,
        category_id: 1,
    },
    {
        id: 10005,
        name: "Beef Jerky Original",
        price: 5.5,
        quantity: 20,
        category_id: 2,
    },
    {
        id: 10006,
        name: "Beef Jerky Miel y Mostaza",
        price: 6.0,
        quantity: 20,
        category_id: 2,
    },
    {
        id: 10007,
        name: "Beef Jerky Teriyaki",
        price: 6.0,
        quantity: 20,
        category_id: 2,
    },
    {
        id: 10008,
        name: "Walnut",
        price: 2,
        quantity: 15,
        category_id: 3,
    },
    {
        id: 10009,
        name: "Walnut",
        price: 2,
        quantity: 15,
        category_id: 3,
    },
    {
        id: 10010,
        name: "Raisin",
        price: 2,
        quantity: 15,
        category_id: 3,
    },
    {
        id: 10011,
        name: "Prune",
        price: 2,
        quantity: 15,
        category_id: 3,
    },
    {
        id: 10012,
        name: "Popcorns",
        price: 5.5,
        quantity: 2,
        category_id: 4,
    },
    {
        id: 10013,
        name: "Granola bars",
        price: 0.5,
        quantity: 25,
        category_id: 5,
    },
    {
        id: 10014,
        name: "Corn",
        price: 1.5,
        quantity: 10,
        category_id: 6,
    },
    {
        id: 10015,
        name: "Potato",
        price: 2.5,
        quantity: 10,
        category_id: 6,
    },
    {
        id: 10016,
        name: "Graham crackers",
        price: 4.5,
        quantity: 10,
        category_id: 7,
    },
    {
        id: 10017,
        name: "Sweet cookies",
        price: 3.5,
        quantity: 10,
        category_id: 7,
    },
    {
        id: 10018,
        name: "Granola",
        price: 4.5,
        quantity: 10,
        category_id: 8,
    },
    {
        id: 10019,
        name: "Protein",
        price: 3.5,
        quantity: 10,
        category_id: 8,
    },
    {
        id: 10020,
        name: "Energy",
        price: 3.5,
        quantity: 10,
        category_id: 7,
    },
    {
        id: 10021,
        name: "Pretzels",
        price: 1.0,
        quantity: 10,
        category_id: 8,
    },
    {
        id: 10022,
        name: "Trail",
        price: 1.0,
        quantity: 10,
        category_id: 9,
    },
    {
        id: 10023,
        name: "Nut",
        price: 1.0,
        quantity: 10,
        category_id: 9,
    },
    {
        id: 10024,
        name: "Seed",
        price: 1.0,
        quantity: 10,
        category_id: 9,
    },
    {
        id: 10025,
        name: "Cheese",
        price: 2.0,
        quantity: 10,
        category_id: 10,
    },
    {
        id: 10026,
        name: "Quinoa",
        price: 2.0,
        quantity: 10,
        category_id: 10,
    },
    {
        id: 10027,
        name: "Rice",
        price: 2.0,
        quantity: 10,
        category_id: 10,
    },
]

export default products;