/api/v1/products:
  get:    
    tags:
      - products        
    responses:
      '200':
        description: List of products
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id: 
                    type: integer
                  name: 
                    type: string
                  price:
                    type: number
                  quantity:
                    type: integer
                  active: 
                    type: boolean
                  category_id:
                    type: integer
                  ProductImages: 
                    type: array
                    items:
                      type: object
                      properties:
                        id: 
                          type: integer
                        path:
                          type: string
                        product_id:
                          type: integer
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
    area: api
  post:    
    tags:
      - products
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              price:
                type: number
              quantity:
                type: integer
              category_id:
                type: integer
      required: true   
    responses:
      '200':
        description: Product object created
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id: 
                    type: integer
                  name: 
                    type: string
                  price:
                    type: number
                  quantity:
                    type: integer
                  active: 
                    type: boolean
                  category_id:
                    type: integer                  
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
    area: api
/api/v1/products/{product_id}:
  parameters:
    - in: path
      name: product_id
      required: true
      type: integer
      description: product id to show details
  get:  
    tags:
      - products        
    responses:
      '200':
        description: Product details
        content:
          application/json:
            schema:
              type: object
              properties:
                id: 
                  type: integer
                name: 
                  type: string
                price:
                  type: number
                quantity:
                  type: integer
                active: 
                  type: boolean
                category_id:
                  type: integer
                ProductImages: 
                  type: array
                  items:
                    type: object
                    properties:
                      id: 
                        type: integer
                      path:
                        type: string
                      product_id:
                        type: integer
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
    area: api
  put:    
    tags:
      - products
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              price:
                type: number
              quantity:
                type: integer
              category_id:
                type: integer
      required: true   
    responses:
      '200':
        description: Product object updated
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id: 
                    type: integer
                  name: 
                    type: string
                  price:
                    type: number
                  quantity:
                    type: integer
                  category_id:
                    type: integer                  
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
    area: api
  delete:    
    tags:
      - products    
    responses:
      '200':
        description: Success message
        content:
          application/json:
            schema:
              type: object
              properties:
                message: 
                  type: string
                  example: The product has been enabled successfully             
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
    area: api
  patch:    
    tags:
      - products  
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              active:
                type: boolean
      required: true     
    responses:
      '200':
        description: Success message
        content:
          application/json:
            schema:
              type: object
              properties:
                message: 
                  type: string
                  example: The product has been enabled successfully            
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
    area: api
/api/v1/products/{product_id}/image:
  parameters:
    - in: path
      name: product_id
      required: true
      type: integer
      description: product id
  put:  
    tags:
      - products   
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              picture:
                type: string
      required: true        
    responses:
      '200':
        description: Success message
        content:
          application/json:
            schema:
              type: object
              properties:
                message: 
                  type: string
                  example: Image saved succesfully   
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
  area: api
/api/v1/products/{product_id}/cart:
  parameters:
    - in: path
      name: product_id
      required: true
      type: integer
      description: product id
  post:  
    tags:
      - products   
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              product_id:
                type: integer
              quantity:
                type: integer
      required: true        
    responses:
      '200':
        description: Success message
        content:
          application/json:
            schema:
              type: object
              properties:
                message: 
                  type: string
                  example: Product added to cart   
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
    area: api
  delete:  
    tags:
      - products       
    responses:
      '200':
        description: Success message
        content:
          application/json:
            schema:
              type: object
              properties:
                message: 
                  type: string
                  example: Product was removed   
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
    area: api
/api/v1/products/{product_id}/reaction:
  parameters:
    - in: path
      name: product_id
      required: true
      type: integer
      description: product id
  post:  
    tags:
      - products   
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              reaction_type_id:
                type: integer
      required: true        
    responses:
      '200':
        description: No message result
        content: null
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
    area: api
/api/v1/products/{product_image_id}/image:
  parameters:
    - in: path
      name: product_image_id
      required: true
      type: integer
      description: Image product id
  get:  
    tags:
      - products       
    responses:
      '200':
        description: Picture of the product
        content: 
          image/*:
            schema: 
              type: string
              format: binary
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '403':
        description: Not Found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      '500':
        description: Internal Server Error
        content: null
    x-codegen-request-body-name: body
    area: api